apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ellamma-ecommerce
  name: ellamma-ecommerce-reader # just can view or read the pods
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]