apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::367012942501:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-WSDeQJ8ei6Ya
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - ellamma-ecommerce-reader 
      userarn: arn:aws:iam::367012942501:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-30T07:09:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1230"
  uid: 305c5953-d313-451f-a77a-7b4f73578bf1
