apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::367012942501:role/eksctl-roboshop-addon-iamserviceaccount-ellam-Role1-y8BPaoL0uy1j
  creationTimestamp: "2026-06-30T13:55:01Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: secret-reader
  namespace: ellamma-ecommerce
  resourceVersion: "72176"
  uid: ac045dfc-ccf7-4b1e-bf53-4157baf79bbe
